"""empty message

Revision ID: 4caf229ccfd8
Revises: fb08a01c93a
Create Date: 2020-09-30 11:09:05.283280

"""

# revision identifiers, used by Alembic.
revision = '4caf229ccfd8'
down_revision = 'fb08a01c93a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    ### end Alembic commands ###
